[build-system]
requires = ["setuptools>=30.3.0",
            "setuptools_scm",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "pytest_astropy/version.py"
